// Command kvbench measures the four numbers docs/verification.md quotes.
//
//	go run ./bench -machine "..." -fs "..." -flush-honoured unknown
//
// Everything it prints is markdown, so the output of one run is exactly the
// contents of bench/results.md. That is deliberate: a benchmark whose published
// numbers are transcribed by hand is a benchmark whose published numbers can
// drift from what the harness actually produces.
//
// The environment flags are not optional in any meaningful sense. A throughput
// figure with no machine and no filesystem behind it is not reproducible and
// is not worth reading, so anything left unset prints as UNRECORDED rather
// than being quietly omitted.
package main

import (
	"flag"
	"fmt"
	"math/rand/v2"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"time"

	"github.com/chickengamer555/kvstore"
)

var (
	machine   = flag.String("machine", "", "CPU and machine this ran on")
	fsys      = flag.String("fs", "", "filesystem the store directory lives on")
	kernel    = flag.String("kernel", "", "kernel or OS build")
	flushHon  = flag.String("flush-honoured", "", "does the disk honour a flush? yes / no / unknown")
	repeats   = flag.Int("repeats", 3, "how many times to run each measurement; the median is reported")
	valueSize = flag.Int("value-size", 128, "value size in bytes")
	dir       = flag.String("dir", "", "where to put the scratch stores (default: a temp dir)")
	ver       = flag.String("version", "working tree", "the kvstore version being measured")
)

func main() {
	flag.Parse()

	root := *dir
	if root == "" {
		var err error
		root, err = os.MkdirTemp("", "kvbench-")
		if err != nil {
			fail(err)
		}
		defer func() { _ = os.RemoveAll(root) }()
	} else if err := os.MkdirAll(root, 0o755); err != nil {
		fail(err)
	}

	g := kvstore.Platform()
	fmt.Printf("# kvstore benchmark\n\n")
	fmt.Printf("Generated by `go run ./bench`. Do not edit by hand.\n\n")
	fmt.Printf("## Environment\n\n")
	fmt.Printf("| | |\n|---|---|\n")
	fmt.Printf("| machine | %s |\n", or(*machine))
	fmt.Printf("| os / arch | %s / %s, %d CPUs |\n", runtime.GOOS, runtime.GOARCH, runtime.NumCPU())
	fmt.Printf("| kernel | %s |\n", or(*kernel))
	fmt.Printf("| filesystem | %s |\n", or(*fsys))
	fmt.Printf("| disk honours flush | %s |\n", or(*flushHon))
	fmt.Printf("| go version | %s |\n", runtime.Version())
	fmt.Printf("| kvstore | %s |\n", *ver)
	fmt.Printf("| ack after fsync | %v |\n", g.AckAfterSync)
	fmt.Printf("| directory fsync | %v |\n", g.DirSync)
	fmt.Printf("| repeats | %d, median reported |\n", *repeats)
	fmt.Printf("| value size | %d bytes |\n", *valueSize)
	fmt.Printf("| date | %s |\n\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Printf("> %s\n\n", g.DirSyncNote)

	fmt.Printf("## Throughput\n\n")
	fmt.Printf("| workload | ops/sec | ns/op |\n|---|---:|---:|\n")

	row("Put, one fsync per call (the honest number)", median(*repeats, func(i int) float64 {
		return benchPut(filepath.Join(root, fmt.Sprint("put", i)), 2000, *valueSize)
	}))
	for _, batch := range []int{10, 100} {
		row(fmt.Sprintf("PutBatch of %d, one fsync per batch (group commit)", batch), median(*repeats, func(i int) float64 {
			return benchBatch(filepath.Join(root, fmt.Sprintf("batch%d-%d", batch, i)), 20000, batch, *valueSize)
		}))
	}
	row("Get against a warm store", median(*repeats, func(i int) float64 {
		return benchGet(filepath.Join(root, fmt.Sprint("get", i)), 20000, 200000, *valueSize)
	}))

	fmt.Printf("\n## Recovery time against log size\n\n")
	fmt.Printf("Checkpointing is disabled for these runs, so the whole log really is replayed.\n")
	fmt.Printf("With checkpointing on, recovery reads at most one checkpoint plus one segment\n")
	fmt.Printf("however long the store has been running, which is the point of clause B6.\n\n")
	fmt.Printf("| records in log | log bytes | recovery | records/sec |\n|---:|---:|---:|---:|\n")
	for _, n := range []int{100, 1000, 10000, 100000} {
		var samples []float64
		var bytes int64
		for i := range *repeats {
			d, b := buildLog(filepath.Join(root, fmt.Sprintf("rec%d-%d", n, i)), n, *valueSize)
			bytes = b
			samples = append(samples, float64(d.Nanoseconds()))
		}
		sort.Float64s(samples)
		ns := samples[len(samples)/2]
		fmt.Printf("| %d | %s | %s | %s |\n", n, human(bytes),
			time.Duration(ns).Round(time.Microsecond), commas(int64(float64(n)/(ns/1e9))))
	}
	fmt.Printf("\nThe smallest row is mostly fixed cost - opening the directory, reading the\n")
	fmt.Printf("checkpoint, creating a segment - rather than replay, which is why its\n")
	fmt.Printf("records/sec figure is so much worse. Replay itself is linear in log bytes.\n")

	whereItLoses()
}

// whereItLoses is printed with the numbers, not kept somewhere they can drift
// apart from. A benchmark that only flatters is a benchmark nobody should
// believe, and the shortest way to be believed is to say where you lose before
// anyone has to ask.
func whereItLoses() {
	fmt.Printf("\n## Where this loses\n\n")
	fmt.Printf("Against any real storage engine, on throughput, by one to three orders of\n")
	fmt.Printf("magnitude. That is the trade, not an oversight.\n\n")
	fmt.Printf("- **Every Put costs an fsync.** RocksDB, LMDB and SQLite in WAL mode all\n")
	fmt.Printf("  default to not doing that, and the gap is most of the difference between\n")
	fmt.Printf("  the first row above and the numbers those engines publish. The comparable\n")
	fmt.Printf("  configuration is sync=true / PRAGMA synchronous=FULL, and even there they\n")
	fmt.Printf("  win on batching, on threading, and on being storage engines rather than\n")
	fmt.Printf("  eight hundred lines of demonstration.\n")
	fmt.Printf("- **Writes are serialised behind one mutex.** There is no concurrency win\n")
	fmt.Printf("  available; the CPU count above is irrelevant to the write path.\n")
	fmt.Printf("- **The whole live key set is in memory**, so a store larger than RAM is\n")
	fmt.Printf("  not a store this can open. The read row reflects that: it is a map\n")
	fmt.Printf("  lookup and a copy with no disk in the path at all, and should be read as\n")
	fmt.Printf("  a measurement of Go's map rather than of a storage engine.\n")
	fmt.Printf("- **No compression, no block cache, no bloom filters, no range scans.**\n")
	fmt.Printf("- **These numbers come from wherever this was run.** If that was not\n")
	fmt.Printf("  Linux, they sit beside durability claims that are only proven on Linux.\n")
	fmt.Printf("  Re-run the harness there before quoting any of it as a Linux figure.\n")
}

func row(label string, opsPerSec float64) {
	fmt.Printf("| %s | %s | %s |\n", label, commas(int64(opsPerSec)), commas(int64(1e9/opsPerSec)))
}

func median(n int, run func(i int) float64) float64 {
	samples := make([]float64, 0, n)
	for i := range n {
		samples = append(samples, run(i))
	}
	sort.Float64s(samples)
	return samples[len(samples)/2]
}

// benchPut is the number that matters: every call separately durable, one
// fsync each, nothing batched and nothing deferred.
func benchPut(dir string, n, valueSize int) float64 {
	s := open(dir, 1<<40)
	defer func() { _ = s.Close() }()
	value := payload(valueSize)

	start := time.Now()
	for i := range n {
		if err := s.Put(key(i), value); err != nil {
			fail(err)
		}
	}
	return float64(n) / time.Since(start).Seconds()
}

func benchBatch(dir string, n, batch, valueSize int) float64 {
	s := open(dir, 1<<40)
	defer func() { _ = s.Close() }()
	value := payload(valueSize)

	entries := make([]kvstore.Entry, 0, batch)
	start := time.Now()
	for i := range n {
		entries = append(entries, kvstore.Entry{Key: key(i), Value: value})
		if len(entries) == batch {
			if err := s.PutBatch(entries); err != nil {
				fail(err)
			}
			entries = entries[:0]
		}
	}
	if len(entries) > 0 {
		if err := s.PutBatch(entries); err != nil {
			fail(err)
		}
	}
	return float64(n) / time.Since(start).Seconds()
}

// benchGet reads a warm store. There is no disk in this path at all - the live
// key set is in memory - so this measures a map lookup and a copy, and it is
// reported for completeness rather than because it is interesting.
func benchGet(dir string, keys, reads, valueSize int) float64 {
	s := open(dir, 1<<40)
	defer func() { _ = s.Close() }()
	value := payload(valueSize)

	entries := make([]kvstore.Entry, 0, keys)
	for i := range keys {
		entries = append(entries, kvstore.Entry{Key: key(i), Value: value})
	}
	if err := s.PutBatch(entries); err != nil {
		fail(err)
	}

	rng := rand.New(rand.NewPCG(1, 2))
	start := time.Now()
	hits := 0
	for range reads {
		if _, ok := s.Get(key(rng.IntN(keys))); ok {
			hits++
		}
	}
	elapsed := time.Since(start)
	if hits != reads {
		fail(fmt.Errorf("bench: %d of %d reads missed; the store is not warm", reads-hits, reads))
	}
	return float64(reads) / elapsed.Seconds()
}

// buildLog writes n records, closes, and times reopening. Checkpointing is off
// so the entire log is replayed.
func buildLog(dir string, n, valueSize int) (time.Duration, int64) {
	s := open(dir, 1<<40)
	value := payload(valueSize)
	entries := make([]kvstore.Entry, 0, 500)
	for i := range n {
		entries = append(entries, kvstore.Entry{Key: key(i), Value: value})
		if len(entries) == 500 {
			if err := s.PutBatch(entries); err != nil {
				fail(err)
			}
			entries = entries[:0]
		}
	}
	if len(entries) > 0 {
		if err := s.PutBatch(entries); err != nil {
			fail(err)
		}
	}
	if err := s.Close(); err != nil {
		fail(err)
	}

	start := time.Now()
	reopened, err := kvstore.Open(dir)
	if err != nil {
		fail(err)
	}
	elapsed := time.Since(start)
	if reopened.Len() != n {
		fail(fmt.Errorf("bench: recovered %d keys, wrote %d", reopened.Len(), n))
	}
	if err := reopened.Close(); err != nil {
		fail(err)
	}
	return elapsed, dirBytes(dir)
}

func open(dir string, checkpointBytes int64) *kvstore.Store {
	s, err := kvstore.OpenWith(kvstore.Options{Dir: dir, CheckpointBytes: checkpointBytes})
	if err != nil {
		fail(err)
	}
	return s
}

func key(i int) string     { return fmt.Sprintf("key-%09d", i) }
func payload(n int) []byte { return []byte(fmt.Sprintf("%*d", n, 0)) }
func or(s string) string {
	if s == "" {
		return "**UNRECORDED**"
	}
	return s
}

func dirBytes(dir string) int64 {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return 0
	}
	var total int64
	for _, e := range entries {
		if info, err := e.Info(); err == nil {
			total += info.Size()
		}
	}
	return total
}

func human(b int64) string {
	switch {
	case b >= 1<<20:
		return fmt.Sprintf("%.1f MiB", float64(b)/(1<<20))
	case b >= 1<<10:
		return fmt.Sprintf("%.1f KiB", float64(b)/(1<<10))
	}
	return fmt.Sprintf("%d B", b)
}

func commas(n int64) string {
	s := fmt.Sprint(n)
	if len(s) <= 3 {
		return s
	}
	var out []byte
	for i, c := range []byte(s) {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, c)
	}
	return string(out)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "bench:", err)
	os.Exit(1)
}
